name: Upload JSON to Supabase Storage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # Example: Run daily at 10:00 AM UTC
  push:
    branches:
      - main

jobs:
  upload-to-supabase:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Supabase Python SDK
      run: |
        pip install supabase requests

    - name: Upload JSON to Supabase Storage
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python - <<EOF
        from supabase import create_client
        import os

        # Initialize Supabase client
        SUPABASE_URL = os.getenv('SUPABASE_URL')
        SUPABASE_KEY = os.getenv('SUPABASE_KEY')
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

        # File to upload
        file_path = "github_trending_repos.json"

        # Verify the file exists before uploading
        if not os.path.exists(file_path):
            print(f"File {file_path} does not exist.")
            exit(1)

        # Upload file to Supabase Storage
        try:
            with open(file_path, "rb") as file:
                file_data = file.read()
                response = supabase.storage.from_('github_trending_json').upload(f"trending/{file_path}", file_data)

            # Check if the upload was successful
            if 'error' not in response:
                print(f"Successfully uploaded {file_path} to Supabase Storage.")
            else:
                print(f"Failed to upload {file_path}. Error: {response['error']}")
                exit(1)
        except Exception as e:
            print(f"An error occurred while uploading the file: {str(e)}")
            exit(1)
        EOF
