name: Upload JSON to Supabase Storage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # Upload daily at 10:00 AM UTC
  push:
    branches:
      - main

jobs:
  upload-to-supabase:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Supabase Python SDK
      run: |
        pip install supabase

    - name: Upload JSON to Supabase Storage
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python - <<EOF
        import os
        from supabase import create_client

        # Initialize Supabase client
        SUPABASE_URL = os.getenv('SUPABASE_URL')
        SUPABASE_KEY = os.getenv('SUPABASE_KEY')
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

        # Find the latest JSON file
        latest_file = sorted([f for f in os.listdir('.') if f.startswith('github_trending_repos_') and f.endswith('.json')])[-1]
        
        # Upload the latest JSON file to Supabase Storage
        with open(latest_file, "rb") as file:
            file_data = file.read()
            response = supabase.storage.from_('github_trending_json').upload(f"trending/{latest_file}", file_data)
        
        if 'error' not in response:
            print(f"Successfully uploaded {latest_file} to Supabase Storage.")
        else:
            print(f"Failed to upload {latest_file}. Error: {response['error']}")
        EOF
