name: Upload JSON to Supabase Storage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # Example: Run daily at 10:00 AM UTC
  push:
    branches:
      - main

jobs:
  upload-to-supabase:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Supabase Python SDK
      run: |
        pip install supabase requests

    - name: Upload JSON to Supabase Storage
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python - <<EOF
        from supabase import create_client
        import os

        # Initialize Supabase client
        SUPABASE_URL = os.getenv('SUPABASE_URL')
        SUPABASE_KEY = os.getenv('SUPABASE_KEY')
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

        # File to upload
        file_path = "github_trending_repos.json"

        # Upload file to Supabase Storage
        with open(file_path, "rb") as file:
            file_data = file.read()
            response = supabase.storage.from_('github_trending_json').upload(f"trending/{file_path}", file_data, upsert=True)

        print(f"Uploaded file: {file_path}, Response: {response}")
        EOF
