name: Upload GitHub Trending JSON to Supabase

on:
  push:
    paths:
      - "github_trending_repos.json"  # Trigger when the JSON file changes

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Supabase Python SDK
      run: |
        pip install supabase-py

    - name: Upload JSON to Supabase Bucket
      run: |
        python - <<EOF
        from supabase import create_client
        import os

        # Initialize Supabase client
        SUPABASE_URL = os.getenv('SUPABASE_URL')
        SUPABASE_KEY = os.getenv('SUPABASE_KEY')
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

        # Path to the JSON file to upload
        file_path = "github_trending_repos.json"
        bucket_name = "github_trending_json"

        # Upload the file to the bucket
        with open(file_path, 'rb') as file_data:
            response = supabase.storage.from_(bucket_name).upload(file_path, file_data, upsert=True)

        print(f"Uploaded {file_path} to Supabase bucket '{bucket_name}' with response: {response}")
        EOF

    - name: Commit and push the changes if necessary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Action"
        git config user.email "actions@users.noreply.github.com"
        git add github_trending_repos.json
        timestamp=$(date -u)
        git commit -m "Uploaded latest GitHub Trending Repositories to Supabase: ${timestamp}" || echo "No changes to commit"
        git push --force
